
CREATE TABLE CONTACTS (
    "CONTACT_ID" INT   NOT NULL,
    "FIRST_NAME" VARCHAR   NOT NULL,
    "LAST_NAME" VARCHAR   NOT NULL,
    "EMAIL" VARCHAR   NOT NULL,
    CONSTRAINT "pk_CONTACTS" PRIMARY KEY (
        "CONTACT_ID"
     )
);

CREATE TABLE CATEGORY (
    "CATEGORY_ID" VARCHAR   NOT NULL,
    "CATEGORY_NAME" VARCHAR   NOT NULL,
    CONSTRAINT "pk_CATEGORY" PRIMARY KEY (
        "CATEGORY_ID"
     )
);

CREATE TABLE SUBCATEGORY (
    "SUBCATEGORY_ID" VARCHAR   NOT NULL,
    "SUBCATEGORY_NAME" VARCHAR   NOT NULL,
    CONSTRAINT "pk_SUBCATEGORY" PRIMARY KEY (
        "SUBCATEGORY_ID"
     )
);

CREATE TABLE CAMPAIGN (
    "CF_ID" INT   NOT NULL,
    "CONTACT_ID" INT   NOT NULL,
    "COMPANY_NAME" VARCHAR   NOT NULL,
    "DESCRIPTION" VARCHAR   NOT NULL,
    "GOAL" FLOAT   NOT NULL,
    "PLEDGED" FLOAT   NOT NULL,
    "OUTCOME" VARCHAR   NOT NULL,
    "BACKERS_COUNT" INT   NOT NULL,
    "COUNTRY" VARCHAR   NOT NULL,
    "CURRENCY" VARCHAR   NOT NULL,
    "LAUNCH_DATE" DATE   NOT NULL,
    "END_DATE" DATE   NOT NULL,
    "CATEGORY_ID" VARCHAR   NOT NULL,
    "SUBCATEGORY_ID" VARCHAR   NOT NULL
);

ALTER TABLE "CAMPAIGN" ADD CONSTRAINT "fk_CAMPAIGN_CONTACT_ID" FOREIGN KEY("CONTACT_ID")
REFERENCES "CONTACTS" ("CONTACT_ID");

ALTER TABLE "CAMPAIGN" ADD CONSTRAINT "fk_CAMPAIGN_CATEGORY_ID" FOREIGN KEY("CATEGORY_ID")
REFERENCES "CATEGORY" ("CATEGORY_ID");

ALTER TABLE "CAMPAIGN" ADD CONSTRAINT "fk_CAMPAIGN_SUBCATEGORY_ID" FOREIGN KEY("SUBCATEGORY_ID")
REFERENCES "SUBCATEGORY" ("SUBCATEGORY_ID");

-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.
